# introduction

Nama : Hernanda Rifaldi

Batch : HCK-037

Objektif : memprediksi kedepresian seseorang dengan model terbaik yang telah dibuat.

# Import Libraries

In [1]:
import re
from pathlib import Path

import numpy as np
import pandas as pd
import joblib

# Loading Model

In [2]:
model_path = Path("artifacts") / "best_model.joblib"
best_model = joblib.load(model_path)

print("Loaded model from:", model_path.resolve())

Loaded model from: C:\Users\guard\HACKTIV8\Phase_1\Milestone\p1-ftds-m2-HRifaldi\artifacts\best_model.joblib

In [7]:
df_raw = pd.read_csv("student_depression_dataset.csv")

def to_snake(s: str) -> str:
    s = s.strip().lower()
    s = s.replace("/", " ")
    s = s.replace("?", "")
    s = re.sub(r"[^0-9a-zA-Z]+", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s

def clean_dataset(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [c.strip() for c in df.columns]

    for c in df.select_dtypes(include="object").columns:
        df[c] = df[c].astype(str).str.strip().str.strip("'").str.strip()

    if "Financial Stress" in df.columns:
        df["Financial Stress"] = df["Financial Stress"].replace("?", np.nan).astype(float)

    df = df.rename(columns={c: to_snake(c) for c in df.columns})
    df = df.rename(columns={
        "have_you_ever_had_suicidal_thoughts": "suicidal_thoughts",
        "family_history_of_mental_illness": "family_history_mental_illness",
    })
    return df

df = clean_dataset(df_raw)


new_data = df.sample(10, random_state=42).drop(columns=["depression"], errors="ignore")
new_data = new_data.drop(columns=["id"], errors="ignore")

display(new_data.head())

,gender,age,city,profession,academic_pressure,work_pressure,cgpa,study_satisfaction,job_satisfaction,sleep_duration,dietary_habits,degree,suicidal_thoughts,work_study_hours,financial_stress,family_history_mental_illness
19981,Female,29.0,Kalyan,Student,2.0,0.0,8.53,3.0,0.0,More than 8 hours,Healthy,B.Arch,No,10.0,5.0,No
16551,Male,28.0,Srinagar,Student,2.0,0.0,5.57,5.0,0.0,7-8 hours,Unhealthy,M.Tech,Yes,3.0,1.0,Yes
7640,Male,34.0,Varanasi,Student,3.0,0.0,5.12,4.0,0.0,More than 8 hours,Moderate,M.Pharm,Yes,4.0,3.0,Yes
21266,Male,21.0,Mumbai,Student,5.0,0.0,8.95,2.0,0.0,Less than 5 hours,Unhealthy,B.Pharm,Yes,8.0,1.0,No
15759,Male,25.0,Visakhapatnam,Student,5.0,0.0,7.87,2.0,0.0,Less than 5 hours,Healthy,B.Ed,No,0.0,3.0,No

# Model Inference Prediction

In [6]:
pred = best_model.predict(new_data)

result = new_data.copy()
result["predicted_depression"] = pred

display(result)

,gender,age,city,profession,academic_pressure,work_pressure,cgpa,study_satisfaction,job_satisfaction,sleep_duration,dietary_habits,degree,suicidal_thoughts,work_study_hours,financial_stress,family_history_mental_illness,predicted_depression
19981,Female,29.0,Kalyan,Student,2.0,0.0,8.53,3.0,0.0,More than 8 hours,Healthy,B.Arch,No,10.0,5.0,No,0
16551,Male,28.0,Srinagar,Student,2.0,0.0,5.57,5.0,0.0,7-8 hours,Unhealthy,M.Tech,Yes,3.0,1.0,Yes,0
7640,Male,34.0,Varanasi,Student,3.0,0.0,5.12,4.0,0.0,More than 8 hours,Moderate,M.Pharm,Yes,4.0,3.0,Yes,0
21266,Male,21.0,Mumbai,Student,5.0,0.0,8.95,2.0,0.0,Less than 5 hours,Unhealthy,B.Pharm,Yes,8.0,1.0,No,1
15759,Male,25.0,Visakhapatnam,Student,5.0,0.0,7.87,2.0,0.0,Less than 5 hours,Healthy,B.Ed,No,0.0,3.0,No,0
27146,Male,24.0,Nagpur,Student,3.0,0.0,6.89,1.0,0.0,5-6 hours,Unhealthy,B.Com,Yes,6.0,1.0,Yes,1
24868,Male,18.0,Vasai-Virar,Student,5.0,0.0,9.88,5.0,0.0,5-6 hours,Moderate,Class 12,Yes,10.0,2.0,Yes,1
26237,Female,24.0,Vasai-Virar,Student,2.0,0.0,7.08,2.0,0.0,Less than 5 hours,Healthy,B.Arch,Yes,12.0,1.0,Yes,1
7260,Male,20.0,Surat,Student,4.0,0.0,6.38,2.0,0.0,5-6 hours,Moderate,Class 12,No,0.0,2.0,Yes,0
19527,Male,32.0,Hyderabad,Student,5.0,0.0,7.10,1.0,0.0,Less than 5 hours,Unhealthy,MCA,Yes,12.0,5.0,Yes,1